export const COCKPIT_FRAME_COUNT = 240;

const frameName = (index: number) =>
  `frame_${String(index).padStart(4, "0")}.webp`;

export const getCockpitFrameSrc = (index: number) =>
  `/cockpit-sequence/${frameName(index)}`;

// Downscaled WebP set (~720px) generated by scripts/generate-mobile-frames.mjs.
// Identical indices to the desktop set, so the loader's frame math is unchanged.
export const getCockpitMobileFrameSrc = (index: number) =>
  `/cockpit-sequence-mobile/${frameName(index)}`;

export const clamp = (value: number, min: number, max: number) =>
  Math.min(Math.max(value, min), max);
